#!/usr/bin/env bash
# Merge `supabase status -o env` into .env.local without clobbering ADMIN_SECRET / CRON_SECRET.
set -euo pipefail
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$DIR/.." && pwd)"
cd "$ROOT"

STATUS="$(pnpm exec supabase status -o env)"

grab() {
  local key="$1"
  printf '%s\n' "$STATUS" | awk -F= -v k="$key" '$1==k {
    sub(/^[^=]+=/,"");
    gsub(/^"/,"");
    gsub(/"$/,"");
    print;
    exit
  }'
}

DB_URL="$(grab DB_URL)"
API_URL="$(grab API_URL)"
ANON_KEY="$(grab ANON_KEY)"
SERVICE_ROLE_KEY="$(grab SERVICE_ROLE_KEY)"

if [ -z "$DB_URL" ] || [ -z "$API_URL" ]; then
  echo "[sync-env] Failed to read supabase status" >&2
  exit 1
fi

ENV_FILE="$ROOT/.env.local"
TMP="$(mktemp)"
touch "$ENV_FILE"

# Keep keys that are not owned by supabase status.
grep -E '^(ADMIN_SECRET|CRON_SECRET|FX_API_BASE)=' "$ENV_FILE" >"$TMP" || true

{
  echo "# Generated by scripts/sync-supabase-env.sh — do not edit the URLs/keys by hand."
  echo "DATABASE_URL=\"$DB_URL\""
  echo "NEXT_PUBLIC_SUPABASE_URL=\"$API_URL\""
  echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=\"$ANON_KEY\""
  echo "SUPABASE_SERVICE_ROLE_KEY=\"$SERVICE_ROLE_KEY\""
  cat "$TMP"
} >"$ENV_FILE.next"

# Defaults if missing
grep -q '^ADMIN_SECRET=' "$ENV_FILE.next" || echo 'ADMIN_SECRET="dev-admin-secret"' >>"$ENV_FILE.next"
grep -q '^CRON_SECRET=' "$ENV_FILE.next" || echo 'CRON_SECRET="dev-cron-secret"' >>"$ENV_FILE.next"
grep -q '^FX_API_BASE=' "$ENV_FILE.next" || echo 'FX_API_BASE="https://api.frankfurter.dev/v1"' >>"$ENV_FILE.next"

mv "$ENV_FILE.next" "$ENV_FILE"
rm -f "$TMP"

echo "[sync-env] Wrote $ENV_FILE"
echo "[sync-env] DATABASE_URL=$DB_URL"
echo "[sync-env] Studio: http://127.0.0.1:54323"
